In [2]:
import torch
import numpy as np

In [15]:
np_data = np.arange(6).reshape((2,3))
torch_data = torch.from_numpy(np_data)

In [17]:
print'\nnumpy:\n',np_data,'\ntorch:\n',torch_data


numpy:
[[0 1 2]
 [3 4 5]] 
torch:
tensor([[0, 1, 2],
        [3, 4, 5]])


In [18]:
tensor2array = torch_data.numpy()
print tensor2array

[[0 1 2]
 [3 4 5]]


In [20]:
data = [-1,1,-4,-3]
tensor = torch.FloatTensor(data)
print tensor
print torch.abs(tensor)

tensor([-1.,  1., -4., -3.])
tensor([1., 1., 4., 3.])


In [22]:
print torch.mean(tensor)

tensor(-1.7500)


In [27]:
data = [[1,2],[3,4]]
tensor = torch.FloatTensor(data)
print np.matmul(data,data)
print torch.mm(tensor, tensor)

[[ 7 10]
 [15 22]]
tensor([[ 7., 10.],
        [15., 22.]])


In [29]:
data = np.array(data)
print data.dot(data)
#print tensor.dot(tensor)

[[ 7 10]
 [15 22]]
