In [20]:
import torch
from torch.autograd import Variable

In [21]:
tensor = torch.FloatTensor([[1,2],[3,4]])
variable = Variable(tensor, requires_grad = True)

In [22]:
print tensor
print variable
print variable*variable

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]], requires_grad=True)
tensor([[ 1.,  4.],
        [ 9., 16.]], grad_fn=<ThMulBackward>)


In [23]:
t_out = torch.mean(tensor*tensor)
v_out = torch.mean(variable*variable)
print t_out
print v_out

tensor(7.5000)
tensor(7.5000, grad_fn=<MeanBackward1>)


In [24]:
v_out.backward()
# v_out = 1/4*sum(var*var)
# d(v_out)/d(var) = 1/4*2*sum(var*var)
print variable.grad
print variable.data
print variable.data.numpy()

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])
tensor([[1., 2.],
        [3., 4.]])
[[1. 2.]
 [3. 4.]]
