In [1]:
import torch
import torch.utils.data as Data

In [26]:
BATCH_SIZE = 8

In [27]:
x = torch.linspace(1, 10, 10)
y = torch.linspace(10, 1, 10)

In [30]:
torch_dataset = Data.TensorDataset(x, y)
loader = Data.DataLoader(
    dataset=torch_dataset,      # torch TensorDataset format
    batch_size=BATCH_SIZE,      # mini batch size
    shuffle=False,               # random shuffle for training
    num_workers=2,              # subprocesses for loading data
)

In [31]:
for epoch in range(3):   # train entire dataset 3 times
    for step, (batch_x, batch_y) in enumerate(loader):  # for each training step
        # train your data...
        print 'Epoch: ', epoch, '| Step: ', step, '| batch x: '
        print batch_x.numpy(), '| batch y: ', batch_y.numpy()
        print '\n'

Epoch:  0 | Step:  0 | batch x: 
[1. 2. 3. 4. 5. 6. 7. 8.] | batch y:  [10.  9.  8.  7.  6.  5.  4.  3.]


Epoch:  0 | Step:  1 | batch x: 
[ 9. 10.] | batch y:  [2. 1.]


Epoch:  1 | Step:  0 | batch x: 
[1. 2. 3. 4. 5. 6. 7. 8.] | batch y:  [10.  9.  8.  7.  6.  5.  4.  3.]


Epoch:  1 | Step:  1 | batch x: 
[ 9. 10.] | batch y:  [2. 1.]


Epoch:  2 | Step:  0 | batch x: 
[1. 2. 3. 4. 5. 6. 7. 8.] | batch y:  [10.  9.  8.  7.  6.  5.  4.  3.]


Epoch:  2 | Step:  1 | batch x: 
[ 9. 10.] | batch y:  [2. 1.]


